### ISSUE TITLE
온프라미스 우분투 설정 config 정리

### ISSUE THREAD

**Issue by ecsimsw** [ecsimsw/daily-notes#64]
### Nvidia gpu / nomodeset
```
# Install Ubuntu 선택 메뉴에서 e
quiet splash --- -> quiet splash nomodeset

# Terminal
$gksudo gedit /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash" -> GRUB_CMDLINE_LINUX_DEFAULT="quiet splash nomodeset"
$sudo update-grub

# Shift 눌러서
linux /boot/vmlinuz~~~ ro quiet_splash $vt_handoff -> linux /boot/vmlinuz~~~ ro nomodeset_$vt_handoff
```

### GNU GRUB 
```
Ubuntu 시작에서 Shift
Advanced options for Ubuntu
(recovery mode)
root

$sudo apt-get update
$sudo apt-get upgrade
$sudo ubuntu-drivers autoinstall
```

### Docker 
```
$sudo apt-get update
$sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
$curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
$sudo apt-get update
$sudo apt-get install docker-ce docker-ce-cli containerd.io
$sudo systemctl status docker
$sudo chmod 666 /var/run/docker.sock
```

### Docker compose 
```
$sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
$sudo chmod +x /usr/local/bin/docker-compose
$sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
$docker-compose --version
```

### Vim
```
$sudo apt-get install vim
```

### Docker thingsboard / In memory message broker
```
$vi docker-compose.yml

version: '3.0'
services:
  thingsboard:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ./data:/data
      - ./logs:/var/log/thingsboard

$mkdir -p ./data && sudo chown -R 799:799 ./data
$mkdir -p ./logs && sudo chown -R 799:799 ./logs
$docker compose up
  ```
